import pystache
from weasyprint import HTML, CSS
import io
import docx
import re

# HELPER: Ensure colors don't have double '##'
def clean_data_colors(data):
    clean = {}
    for key, value in data.items():
        if isinstance(value, str) and (key.endswith("color") or "color" in key):
            # If template assumes {{color}} has no hash, but we provide one, strip it?
            # Actually simpler: standard vars should have hash.
            # But we handle specific cleaning logic here if needed.
            clean[key] = value
        else:
            clean[key] = value
    return clean

# 1. HTML/PDF GENERATOR
def create_pdf_from_template(template_html: str, template_css: str, cv_data: dict) -> bytes:
    # PRE-PROCESSING CSS
    # If variables are None, use defaults to prevent crashes
    render_data = {
        **cv_data,
        "accent_color": cv_data.get("accent_color") or "#2c3e50",
        "text_color": cv_data.get("text_color") or "#333333",
        "font_family": cv_data.get("font_family") or "sans-serif"
    }

    # Render Template Strings
    rendered_html = pystache.render(template_html, render_data)
    rendered_css = pystache.render(template_css, render_data)

    # 🚨 FINAL SAFETY CLEANUP: Remove double hashes '##' generated by bad merging
    rendered_css = rendered_css.replace("##", "#")

    # GENERATE PDF
    html = HTML(string=rendered_html)
    css = CSS(string=rendered_css)
    
    # Render PDF bytes
    return html.write_pdf(stylesheets=[css])

# 2. DOCX GENERATOR
def create_docx_from_data(cv_data: dict) -> bytes:
    document = docx.Document()
    
    # HEADER
    document.add_heading(cv_data.get('fullName', 'Name'), 0)
    p = document.add_paragraph(cv_data.get('jobTitle', 'Role'))
    p = document.add_paragraph(f"{cv_data.get('email', '')} | {cv_data.get('phone', '')}")

    # SECTIONS
    for section in ['summary', 'experience', 'education']:
        if cv_data.get(section):
            document.add_heading(section.capitalize(), level=1)
            # Handle text with newlines
            text_block = cv_data.get(section, "")
            # If it's a string representation of bullets, clean it
            clean_text = text_block.replace("<ul>", "").replace("</ul>", "").replace("<li>", "• ").replace("</li>", "\n")
            document.add_paragraph(clean_text)

    # SKILLS
    if cv_data.get('skills'):
        document.add_heading('Skills', level=1)
        skills_str = cv_data.get('skills', "")
        # If array vs string handling
        if isinstance(skills_str, list):
            skills_str = ", ".join(skills_str)
        document.add_paragraph(skills_str)

    # SAVE TO BUFFER
    file_stream = io.BytesIO()
    document.save(file_stream)
    file_stream.seek(0)
    return file_stream.read()
